---
- name: Bring up a new DOAJ application server
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    digitalocean_token: "{{ lookup('ansible.builtin.env', 'DIGITALOCEAN_TOKEN') }}"
    server_config: "{{ lookup('ansible.builtin.file', '../../cloud-init_userdata/doaj-app_cloud-config.txt') }}"
    droplet_name: doaj-public-1
    #droplet_name: doaj-background-1
    #droplet_name: doaj-editor-1
  
  tasks:

    - name: Create Droplet with root access Steve and Rama, using app server userdata
      digitalocean.cloud.droplet:
        state: present
        token: "{{ digitalocean_token }}"
        name: '{{droplet_name}}'
        region: lon1
        size: c-4
        #size: s-4vcpu-8gb
        #size: s-2vcpu-4gb
        tags:
          - doaj-test
          - firewall-web-ssh
        image: ubuntu-22-04-x64
        # Run task list_ssh_keys.yml to get the key IDs
        ssh_keys: ["30242381", "40223915"]
        ipv6: true
        unique_name: true
        monitoring: true
        backups: false
        with_droplet_agent: true
        user_data: "{{ server_config }}"

    - name: Get info on our new droplet to get the IP
      digitalocean.cloud.droplets_info:
        name: '{{droplet_name}}'
      register: dropletinfo

    - name: Parse out the assigned IP
      ansible.builtin.set_fact:
        public_ip: "{{ dropletinfo['droplets'][0]['networks']['v4'] | selectattr('type', '==', 'public') | map(attribute='ip_address') | first }}"
        droplet_id: "{{ dropletinfo['droplets'][0]['id'] }}"
    
    - name: Assign the new droplet to the DOAJ project using doctl
      local_action: ansible.builtin.command doctl projects resources assign f7668431-327e-47d8-9d7e-73e713fe1d4d --resource=do:droplet:{{ droplet_id }}

    - name: Output a summary including login command
      ansible.builtin.debug:
        msg: "App server created: cloo@{{public_ip}}"