---
- name: Import index data to elasticsearch
  hosts: "{{ target if target is defined and target | length > 0 else 'all:!index' }}"
  gather_facts: yes

  vars:
    ansible_user: "cloo"

  tasks:
    - name: Run Python script in a screen session
      shell: |
        screen -dmS init_import_data bash -c 'cd /home/{{ansible_user}}/doaj && DOAJENV="test" /home/{{ansible_user}}/doaj/venv/bin/python -u portality/scripts/anon_import.py data_import_settings/test_server.json > ~/init_anon_import_output.log 2>&1'
      environment:
        TERM: xterm
