#!/bin/bash
# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m 	h	dom 	mon 	dow	command
*/30	*	* 	* 	*	export DOAJENV=production ; /opt/doaj/bin/python /opt/doaj/src/doaj/portality/scripts/ingestarticles.py >> /home/cloo/cron-logs/doaj-ingest-articles_`date +\%F_\%H\%M`.log 2>&1
*/30	*	* 	*	*	export DOAJENV=production ; /opt/doaj/bin/python /opt/doaj/src/doaj/portality/scripts/journalcsv.py >> /home/cloo/cron-logs/doaj-journal-csv_`date +\%F_\%H\%M`.log 2>&1
0	2	* 	* 	*	export DOAJENV=production ; /opt/doaj/bin/python /opt/doaj/src/doaj/portality/scripts/toc.py >> /home/cloo/cron-logs/doaj-toc_`date +\%F_\%H\%M`.log 2>&1
0	*	*	*	*	export NOW=`date +\%F_\%H\%M\%S` ; echo "timestamp $NOW" >> /home/cloo/backups/logs/oag-publishers.log 2>&1 && cd /home/cloo/backups/oag-publishers-and-licenses && /usr/bin/node --nouse-idle-notification --expose-gc /home/cloo/elasticsearch-exporter -i oag -t publisher -g publisher_"$NOW" -m 0.3 >> /home/cloo/backups/logs/oag-publishers.log 2>&1 && /usr/bin/s3cmd put -H --acl-private --no-delete-removed publisher_"$NOW".data s3://oag-publishers-and-licenses >> /home/cloo/backups/logs/oag-publishers.log 2>&1
0	*	*	*	*	export NOW=`date +\%F_\%H\%M\%S` ; echo "timestamp $NOW" >> /home/cloo/backups/logs/oag-licenses.log 2>&1 && cd /home/cloo/backups/oag-publishers-and-licenses && /usr/bin/node --nouse-idle-notification --expose-gc /home/cloo/elasticsearch-exporter -i oag -t license_statement -g license_statement_"$NOW" -m 0.3 >> /home/cloo/backups/logs/oag-licenses.log 2>&1 && /usr/bin/s3cmd put -H --acl-private --no-delete-removed license_statement_"$NOW".data s3://oag-publishers-and-licenses >> /home/cloo/backups/logs/oag-licenses.log 2>&1

