---
- hosts: all:!test
  tasks:
    - name: Ping all production hosts to check we're fully up and running
      ping:

- hosts: all:!test
  tasks:
    - name: Reboot metricbeat on all production servers
      systemd:
        state: restarted
        name: metricbeat
      become: yes

- hosts: doaj-public-1
  tasks:
    - name: Reboot filebeat on the primary app server
      systemd:
        state: restarted
        name: filebeat
      become: yes
