---

- hosts: all
  tasks:
    - name: Upload SSH public key 'cl-doaj.pub' to DOAJ machines
      authorized_key:
        user: cloo
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/cl-doaj.pub') }}"
